### ISSUE TITLE
Duplicate text into two languages

### ISSUE THREAD

**Issue by Danil42Russia** [VKCOM/statshouse#1307]
@olganaumenko, I accidentally found that in the [component documentation](https://vkcom.github.io/statshouse/ru/overview/components) the text on the page is duplicated in Russian and English. 

<img width="890" alt="Screenshot 2024-07-10 at 21 06 04" src="https://github.com/VKCOM/statshouse/assets/6605618/b7bb2ffa-b398-4bb3-abfd-5f467d4f4e39">

**Comment by olganaumenko** [comment]
Please verify if the issue is fixed:
https://vkcom.github.io/statshouse/ru/overview/components/

<img width="852" alt="Снимок экрана 2024-07-11 в 12 52 58" src="https://github.com/VKCOM/statshouse/assets/64418523/13ca3521-bb6b-4dfd-b693-ae0d8b4073fc">

**Comment by Danil42Russia** [comment]
Yes, it looks like it should. Thank you! :)
