### ISSUE TITLE
ui: show last point in legend when no hover

### ISSUE THREAD

**Issue by flyingmutant** [VKCOM/statshouse#156]
Much more useful than an empty legend.

**Comment by flyingmutant** [comment]
To avoid situations like this (look at percentages):

![Screenshot from 2023-01-23 20-52-13](https://user-images.githubusercontent.com/73059/214113096-7228c146-592d-4386-a6ff-4fd6f868b8b9.png)

we can show an extra column, in which show human-readable information (`5s ago`, `12h 4m ago`) about how far is the last point on the graph.

**Comment by leeoniya** [comment]
probably needs some core API additions: https://github.com/leeoniya/uPlot/issues/644

**Comment by leeoniya** [comment]
fixed in https://github.com/leeoniya/uPlot/commit/e04d41161f19bf90fdf7d289f90aacde839a5c27
