### ISSUE TITLE
OpenMetrics

### ISSUE THREAD

**Issue by spatecon** [VKCOM/statshouse#5]
Thanks for letting us use the product as open source.

I'm wondering if there are any plans on OpenMetrics (aka Prometheus) metrics format support? I hope it would move project in list of mature ones.

**Comment by flyingmutant** [comment]
Hey! We already have some prototype code for both scraping Prometheus/OpenMetrics format as well as receiving Prometheus Remote Write requests -- Prometheus compatibility is obviously a must have for broader adoption, including the whole of VK (outside VKontakte).

We will announce Prometheus compatibility after we have battle-tested it enough internally to make sure it is a real first-class feature and not an inferior "we also do this" thing.

**Comment by flyingmutant** [comment]
Closing in favor of #111.
